services:
  ha-huff-proxy:
    container_name: ha-huff-proxy
    build: .
    network_mode: host
    environment:
      - OUTPUT_DIR=/app/output
    volumes:
      - config/www:/app/output
    restart: unless-stopped
